### ISSUE TITLE
Need to get pointing position info to backends

### ISSUE THREAD

**Issue by david-macmahon** [UCBerkeleySETI/meerkat-backend-interface#11]
How will we get pointing position info to the backend?  This is needed for target selector logic as well as beamformer delay/phase offset calculations.

**Comment by danielczech** [comment]
At the moment, the current target coordinates are published to the `sensor_alerts` channel by the `katportal_server`, to which the target selector is subscribed. What would be the best way to convey this information to the backends?

**Comment by danielczech** [comment]
Currently publishing `RA_STR` and `DEC_STR` (see 32fb552 and 20f88ae).
