### ISSUE TITLE
Print startup banner to stdout only to ttys

### ISSUE THREAD

**Issue by david-macmahon** [UCBerkeleySETI/meerkat-backend-interface#13]
Some of the meerkat-backend-interface processes print a very aesthetically appealing banner on stdout when they start, complete with ASCII art.  When run in as a daemon, these banners just go to log files where they consume disk space. These scripts should only output the banner when stdout is going to a tty.

**Comment by david-macmahon** [comment]
```
import sys
if sys.stdout.isatty():
    # print banner
```

**Comment by danielczech** [comment]
Fixed in 845ad0e for `meerkat-backend-interface`.
