### ISSUE TITLE
Coordinator should set DATADIR

### ISSUE THREAD

**Issue by david-macmahon** [UCBerkeleySETI/meerkat-backend-interface#22]
The Coordinator should set DATADIR to `/buf0/YYYYMMDD/NNNN`, where `YYYYMMDD` and `NNNN` are from the `YYYYMMDD-NNNN` MeerKAT schedule block ID for an observation.

**Comment by danielczech** [comment]
Implemented in 36e69e7 and 1200d2f and tested during BLUSE engineering time.
