### ISSUE TITLE
Coordinator needs to publish frequency info

### ISSUE THREAD

**Issue by david-macmahon** [UCBerkeleySETI/meerkat-backend-interface#9]
The Coordinator needs to publish some frequency reference point so that the backends will be able to calculate OBSFREQ from SCHAN, OBSNCHAN (== NANTS*NSTRM*HNCHAN), and CHAN_BW.  Not sure what frequency info is available from CAM, but we should probably pass it through with minimal modifications/derivations.  Probably best to come up with a single scheme that will work for all bands (if possible)

**Comment by danielczech** [comment]
Publishing the centre frequency as `CENTFREQ` to the processing nodes; see a6d3d3d and d3d3bc7. This should work for all bands.
